name: Build and Output Artifact

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node@22
              uses: actions/setup-node@v3
              with:
                  node-version: 22
            
            - name: Install dependencies
              run: |
                  npm ci
            
            - name: Build
              run: |
                  npm run build
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: index.js
                  path: ./out/index.js